kind: pipeline
name: default

platform:
  os: linux

steps:
- name: generate tags
  image: alpine:3.12
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - sh gen-tags.sh $${DRONE_STAGE_ARCH} > .tags

- name: docker
  image: plugins/docker
  settings:
    repo: ghcr.io/rkojedzinszky/postgres-patroni
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    mirror:
      from_secret: hub_docker_mirror
