kind: pipeline
name: default
type: kubernetes

steps:
- name: generate tags
  image: alpine:3.13
  pull: always
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - sh gen-tags.sh $${DRONE_STAGE_ARCH} > .tags

- name: docker
  image: plugins/docker
  pull: always
  settings:
    repo: ghcr.io/rkojedzinszky/postgres-patroni
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
    - name: docker
      path: /var/lib/docker

volumes:
  - name: docker
    temp: {}
