---
kind: pipeline
name: manifest
type: kubernetes

platform:
  os: linux

steps:
- name: generate tags
  image: alpine:3.13
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - sh gen-tags.sh > .tags

- image: plugins/manifest
  settings:
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
