name: Container Image CI

on:
  push:
    branches:
      - github
    tags:
      - "*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - DEBIAN_DIST: buster
            POSTGRES_MAJOR: 11
          - DEBIAN_DIST: bullseye
            POSTGRES_MAJOR: 13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup additional tags
        id: tags
        run: |
          echo "::set-output name=DATE::$(date +%Y%m%d)"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern=${{ matrix.POSTGRES_MAJOR }}-{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=${{ matrix.POSTGRES_MAJOR }}-{{major}}.{{minor}}-${{ steps.tags.outputs.DATE }}
            type=semver,pattern=${{ matrix.POSTGRES_MAJOR }}-{{major}}-${{ steps.tags.outputs.DATE }}
            type=raw,value=${{ matrix.POSTGRES_MAJOR }}
            type=raw,value=${{ matrix.POSTGRES_MAJOR }}-${{ steps.tags.outputs.DATE }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            DEBIAN_DIST=${{ matrix.DEBIAN_DIST }}
            POSTGRES_MAJOR=${{ matrix.POSTGRES_MAJOR }}
          platforms: linux/amd64, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
