name: Container Image CI

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup additional tags
        id: tags
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}-${{ steps.tags.outputs.DATE }}
            type=semver,pattern={{major}}-${{ steps.tags.outputs.DATE }}
            type=raw,value=${{ steps.tags.outputs.DATE }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
